apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMk9USTBNalk0T1N3aWFXRjBJam94TnpZNU1qUXlOamc1ZlEudFVudm9yRmJKM1ByZ1FKUEwyMzRueWk1cFhWQTRNUGNkS3ZUX1dMdi1jNAo=
